name: 'helm-push-action'
description: 'package and publish your helm chart to a registry, e.g. chartmuseum or harbor'
author: 'romnnn'
branding:
  color: 'blue'
  icon: 'upload-cloud'
inputs: 
  charts-dir:
    description: 'directory containing the charts directories to upload, e.g. ./charts'
    required: false
    default: '.'
  chart-name:
    description: 'directory containing the chart'
    required: true
  chart-version:
    description: 'chart version'
    required: false
  app-version:
    description: 'app version'
    required: false
  force:
    description: 'force upload of the chart even if the version already exists'
    required: false
    default: false
  user:
    description: 'helm registry user'
    required: true
  password:
    description: 'helm registry password'
    required: true
  registry:
    description: 'helm registry'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  # image: 'dockerfile.wrapper'
  env:
    CHART_DIR: ${{ inputs.charts-dir }}
    CHART: ${{ inputs.chart-name }}
    CHART_VERSION: ${{ inputs.chart-version }}
    APP_VERSION: ${{ inputs.app-version }}
    FORCE: ${{ inputs.force }}
    USER: ${{ inputs.user }}
    PASSWORD: ${{ inputs.password }}
    REGISTRY: ${{ inputs.registry }}
