name: build 
on: ['push']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build docker action container
      run: docker build -t helm-push-action .
    - name: test helm binary
      run: docker run --rm -i --entrypoint=helm helm-push-action version -c
    - name: test helm push plugin
      run: docker run --rm -i --entrypoint=helm helm-push-action push --help
